.pragma library

// The emoji picker's list (Win+. in Launcher.qml): emoji, Korean name, search words.
// The most used ones, roughly in the order Windows' emoji panel shows them.
var list = [
    ["😀", "활짝 웃는 얼굴", "웃음 행복 기쁨 smile grin happy"],
    ["😂", "기뻐서 우는 얼굴", "웃김 ㅋㅋ 눈물 lol laugh joy tears"],
    ["🤣", "데굴데굴 웃는 얼굴", "웃김 ㅋㅋㅋ rofl laugh"],
    ["😊", "미소 짓는 얼굴", "미소 웃음 수줍 smile blush"],
    ["😍", "하트 눈", "사랑 좋아 반함 love heart eyes"],
    ["🥰", "하트 둘러싼 얼굴", "사랑 행복 love hearts"],
    ["😘", "뽀뽀하는 얼굴", "뽀뽀 키스 사랑 kiss"],
    ["😉", "윙크", "윙크 장난 wink"],
    ["😎", "선글라스", "멋짐 쿨 cool sunglasses"],
    ["🤔", "생각하는 얼굴", "생각 고민 흠 thinking hmm"],
    ["🙄", "눈 굴리는 얼굴", "어이없음 짜증 eye roll"],
    ["😅", "식은땀 웃음", "민망 땀 머쓱 sweat smile"],
    ["😆", "눈 감고 웃는 얼굴", "웃음 ㅋㅋ laugh"],
    ["🙂", "살짝 웃는 얼굴", "미소 smile slight"],
    ["🙃", "거꾸로 얼굴", "장난 거꾸로 upside down"],
    ["😐", "무표정", "무표정 그냥 neutral"],
    ["😴", "자는 얼굴", "잠 졸림 피곤 sleep zzz"],
    ["😪", "졸린 얼굴", "졸림 피곤 sleepy"],
    ["😢", "우는 얼굴", "슬픔 눈물 ㅠㅠ cry sad"],
    ["😭", "엉엉 우는 얼굴", "슬픔 눈물 ㅠㅠ 통곡 sob cry"],
    ["😡", "화난 얼굴", "화남 분노 angry mad"],
    ["😱", "비명 지르는 얼굴", "놀람 충격 무서움 scream shock"],
    ["😮", "입 벌린 얼굴", "놀람 헉 wow surprised"],
    ["🤯", "머리 터지는 얼굴", "충격 대박 mind blown"],
    ["😳", "얼굴 빨개짐", "당황 부끄 flushed"],
    ["🥺", "부탁하는 얼굴", "부탁 제발 애원 pleading"],
    ["😬", "이 드러낸 얼굴", "어색 grimace awkward"],
    ["🤗", "안아 주는 얼굴", "포옹 안아 hug"],
    ["🤭", "입 가리고 웃는 얼굴", "웃음 비밀 giggle"],
    ["🤫", "쉿", "조용 비밀 shh quiet"],
    ["🤐", "입 다문 얼굴", "비밀 지퍼 zipper"],
    ["😷", "마스크 쓴 얼굴", "아픔 감기 마스크 sick mask"],
    ["🤒", "열나는 얼굴", "아픔 감기 열 sick fever"],
    ["🤮", "토하는 얼굴", "토 역겨움 vomit"],
    ["🥳", "파티 얼굴", "축하 파티 생일 party celebrate"],
    ["🤓", "안경 쓴 얼굴", "공부 너드 nerd"],
    ["😇", "천사 얼굴", "천사 착함 angel halo"],
    ["😈", "악마 얼굴", "악마 장난 devil"],
    ["💀", "해골", "해골 죽음 웃겨죽음 skull dead"],
    ["👻", "유령", "유령 귀신 ghost"],
    ["🤖", "로봇", "로봇 robot bot"],
    ["👽", "외계인", "외계인 alien"],
    ["💩", "똥", "똥 poop"],
    ["👍", "좋아요", "좋아 최고 추천 굿 like thumbs up ok"],
    ["👎", "싫어요", "싫어 별로 dislike thumbs down"],
    ["👏", "박수", "박수 짝짝 clap"],
    ["🙏", "두 손 모음", "부탁 감사 기도 please thanks pray"],
    ["👌", "오케이", "좋아 오케이 ok"],
    ["✌️", "브이", "브이 평화 victory peace"],
    ["🤞", "행운을 빌어", "행운 기원 fingers crossed luck"],
    ["👋", "손 흔들기", "안녕 인사 hi bye wave"],
    ["💪", "힘", "힘 근육 화이팅 strong muscle"],
    ["🙌", "만세", "만세 축하 hooray"],
    ["🤝", "악수", "악수 협력 handshake deal"],
    ["👉", "오른쪽 가리키기", "가리키기 이쪽 point right"],
    ["👀", "눈", "봐 보는중 눈 eyes look"],
    ["🧠", "뇌", "뇌 생각 brain"],
    ["❤️", "빨간 하트", "하트 사랑 heart love red"],
    ["🧡", "주황 하트", "하트 heart orange"],
    ["💛", "노란 하트", "하트 heart yellow"],
    ["💚", "초록 하트", "하트 heart green"],
    ["💙", "파란 하트", "하트 heart blue"],
    ["💜", "보라 하트", "하트 heart purple"],
    ["🖤", "검은 하트", "하트 heart black"],
    ["💔", "깨진 하트", "이별 실연 broken heart"],
    ["💕", "하트 두 개", "하트 사랑 hearts"],
    ["✨", "반짝반짝", "반짝 빛 새것 sparkles"],
    ["🔥", "불", "불 대박 핫 인기 fire hot lit"],
    ["💯", "100점", "백점 완벽 최고 hundred perfect"],
    ["⭐", "별", "별 즐겨찾기 star"],
    ["🎉", "폭죽", "축하 파티 생일 party tada"],
    ["🎂", "생일 케이크", "생일 케이크 축하 birthday cake"],
    ["🎁", "선물", "선물 생일 gift present"],
    ["💡", "전구", "아이디어 전구 idea bulb"],
    ["✅", "체크 표시", "완료 확인 체크 done check yes"],
    ["❌", "엑스 표시", "틀림 아니 취소 x no wrong"],
    ["⚠️", "경고", "경고 주의 warning"],
    ["❓", "물음표", "질문 물음표 question"],
    ["❗", "느낌표", "느낌표 중요 exclamation"],
    ["💬", "말풍선", "대화 채팅 말 chat speech"],
    ["📌", "압정", "고정 핀 중요 pin"],
    ["📎", "클립", "첨부 클립 paperclip attach"],
    ["📝", "메모", "메모 필기 note memo"],
    ["📅", "달력", "달력 일정 날짜 calendar"],
    ["⏰", "알람 시계", "알람 시계 시간 alarm clock"],
    ["💻", "노트북", "컴퓨터 노트북 laptop computer"],
    ["🖥️", "데스크톱 컴퓨터", "컴퓨터 모니터 desktop pc"],
    ["📱", "휴대폰", "폰 휴대폰 스마트폰 phone mobile"],
    ["⌨️", "키보드", "키보드 keyboard"],
    ["🐧", "펭귄", "펭귄 리눅스 linux penguin tux"],
    ["🔒", "자물쇠", "잠금 보안 비밀 lock security"],
    ["🔑", "열쇠", "열쇠 키 비밀번호 key password"],
    ["🛡️", "방패", "방패 보안 보호 shield security"],
    ["🐛", "벌레", "버그 벌레 bug"],
    ["🚀", "로켓", "로켓 출시 빠름 rocket launch"],
    ["☕", "커피", "커피 카페 coffee"],
    ["🍕", "피자", "피자 pizza"],
    ["🍗", "치킨", "치킨 닭 chicken"],
    ["🍺", "맥주", "맥주 술 beer"],
    ["🍚", "밥", "밥 식사 rice"],
    ["🐶", "강아지", "강아지 개 멍멍 dog puppy"],
    ["🐱", "고양이", "고양이 냥 cat"],
    ["🌸", "벚꽃", "꽃 벚꽃 봄 flower blossom"],
    ["☀️", "해", "해 맑음 날씨 sun sunny"],
    ["🌧️", "비", "비 날씨 rain"],
    ["❄️", "눈송이", "눈 겨울 추움 snow cold"],
    ["🌙", "달", "달 밤 moon night"],
    ["🇰🇷", "대한민국", "한국 태극기 korea flag"],
    ["⚽", "축구공", "축구 공 soccer football"],
    ["🎮", "게임", "게임 패드 game gaming"],
    ["🎵", "음표", "음악 노래 music note"],
    ["📷", "카메라", "사진 카메라 camera photo"],
    ["💰", "돈 가방", "돈 부자 money"],
    ["🏠", "집", "집 home house"]
];
