#!/usr/bin/env bash

iso_name="robinos"
iso_label="ROBINOS_$(date +%Y%m)"
iso_publisher="RobinOS <https://example.invalid/robinos>"
iso_application="RobinOS Security Learning Live ISO"
iso_version="$(date +%Y.%m.%d)"
install_dir="robinos"
buildmodes=("iso")
bootmodes=("bios.syslinux" "uefi.grub")
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=("-comp" "xz" "-Xbcj" "x86" "-b" "1M" "-Xdict-size" "1M")
file_permissions=(
  # Kept from the releng profile this one replaces
  ["/etc/shadow"]="0:0:400"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/root/.gnupg"]="0:0:700"
  ["/usr/local/bin/choose-mirror"]="0:0:755"
  ["/usr/local/bin/Installation_guide"]="0:0:755"
  ["/usr/local/bin/livecd-sound"]="0:0:755"
  # RobinOS
  ["/root"]="0:0:750"
  ["/root/customize_airootfs.sh"]="0:0:755"
  ["/usr/local/bin/robinctl"]="0:0:755"
  ["/usr/local/bin/robin-install"]="0:0:755"
  ["/opt/robinos/bin/robinctl"]="0:0:755"
  ["/opt/robinos/scripts/build-iso.sh"]="0:0:755"
  ["/opt/robinos/scripts/build-in-arch-container.sh"]="0:0:755"
  ["/opt/robinos/scripts/check-arch-packages.sh"]="0:0:755"
  ["/opt/robinos/scripts/clean-build.sh"]="0:0:755"
  ["/opt/robinos/scripts/doctor-build.sh"]="0:0:755"
  ["/opt/robinos/scripts/customize-iso-boot.sh"]="0:0:755"
  ["/opt/robinos/scripts/install-branding.sh"]="0:0:755"
  ["/opt/robinos/scripts/install-robinctl.sh"]="0:0:755"
  ["/opt/robinos/scripts/post-install.sh"]="0:0:755"
  ["/opt/robinos/scripts/prepare-archiso.sh"]="0:0:755"
  ["/opt/robinos/scripts/run-vm.sh"]="0:0:755"
  ["/opt/robinos/scripts/sync-archiso-files.sh"]="0:0:755"
  ["/opt/robinos/scripts/install-desktop.sh"]="0:0:755"
  ["/opt/robinos/scripts/fetch-fonts.sh"]="0:0:755"
  ["/opt/robinos/scripts/check-desktop.sh"]="0:0:755"
  ["/opt/robinos/scripts/boot-test.sh"]="0:0:755"
  ["/opt/robinos/desktop/bin/robinos-session"]="0:0:755"
  ["/opt/robinos/desktop/bin/robinos-shell"]="0:0:755"
  ["/usr/share/robinos/bin/robinos-shell"]="0:0:755"
  ["/opt/robinos/desktop/bin/robinos-vm-display"]="0:0:755"
  ["/usr/share/robinos/bin/robinos-vm-display"]="0:0:755"
  ["/opt/robinos/desktop/bin/robinos-screenshot"]="0:0:755"
  ["/usr/share/robinos/bin/robinos-session"]="0:0:755"
  ["/usr/share/robinos/bin/robinos-screenshot"]="0:0:755"
  ["/opt/robinos/desktop/bin/robinos-os-release"]="0:0:755"
  ["/usr/share/robinos/bin/robinos-os-release"]="0:0:755"
)
