#
# ~/.bashrc (RobinOS)
#
# The RobinOS prompt, Windows command hints and greeting come from
# /usr/share/robinos/bash/robinos-bashrc.sh. Put your own settings below it.

# Only interactive shells
[[ $- != *i* ]] && return

[[ -r /usr/share/robinos/bash/robinos-bashrc.sh ]] && . /usr/share/robinos/bash/robinos-bashrc.sh
